### ISSUE TITLE
/vanish doesn't seem to work as a toggle any longer

### ISSUE THREAD

**Issue by BlackXRed** [EricRabil/tregmine#5]
It reports "You are currently visible." after each usage and never toggles over into invisible.

**Comment by EricRabil** [comment]
@BlackXRed are you giving arguments?

**Comment by BlackXRed** [comment]
doh!  I forgot the behavior had changed in the last version.  (and no arguments doesn't show the on|off text)  Thx.

**Comment by EricRabil** [comment]
@BlackXRed I'll update the code so it gives arguments
